# Generated by Django 3.2.8 on 2021-10-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211020_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisticket',
            name='task_id',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
