name: "Build project and containers and cache them in Cachix"
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Use the cache
      uses: cachix/cachix-action@v10
      with:
        name: justice-tristan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run the CI set
      run: nix-build -A ci
