name: "Build public TRISTAN storybook on GitHub Pages"
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Use the cache
      uses: cachix/cachix-action@v10
      with:
        name: justice-tristan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install frontend dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: nix-shell default.nix -A ciShell --run "npm install"
    - name: Build TRISTAN standalone frontend bundles
      run: nix-shell default.nix -A ciShell --run "npx nx run tristan-core:build-storybook"
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: dist/storybook/tristan-core
        target-folder: storybook
        clean: true
