name: "Test the project"
on:
  pull_request:
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Use the cache
      uses: cachix/cachix-action@v10
      with:
        name: justice-tristan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell default.nix -A ciShell --run "npm test"
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Use the cache
      uses: cachix/cachix-action@v10
      with:
        name: justice-tristan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell default.nix -A ciShell --run "pytest"
